# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VTBHack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VTBHack
  pod 'Alamofire'
  pod 'CryptoSwift'
  pod 'Texture'
  pod 'IQKeyboardManagerSwift'
end
